### ISSUE TITLE
Issue with feature 506: Add batch action to allow sharing with multiple guests at once

### ISSUE THREAD

**Issue by jmeile** [owncloud/guests#519]
### Steps to reproduce
1. Install Guest version 0.11.0 from the Market place
2. Try to share a folder to diffent email addresses, eg: my_mail1@domain.com,my_mail2@domain.com
3. You will see the error: "No users or groups found for my_mail1@domain.com,my_mail2@domain.com"

### Expected behaviour
It should create both users and send the set password link to both email addresses

### Actual behaviour
The error message: "No users or groups found for my_mail1@domain.com,my_mail2@domain.com" is shown

### Server configuration
**Operating system**: Ubuntu 20.04.5 LTS

**Web server:** Apache 2.4.41-4ubuntu3.12

**Database:** mysql-server 8.0.30-0ubuntu0.20.04.2

**PHP version:** 7.4+75

**ownCloud version:** 10.10.0.3

**Updated from an older ownCloud or fresh install:** 10.8.0

**Where did you install ownCloud from:** It was installed according to the instructions:
https://doc.owncloud.com/server/next/admin_manual/maintenance/upgrading/manual_upgrade.html

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.

No errors have been found.
```

**The content of config/config.php:**

```
See attachment
```

**List of activated apps:**

```
Enabled:
  - activity:
    - Version: 2.7.0
    - Path: /home/owncloud/apps/activity
  - brute_force_protection:
    - Version: 1.1.0
    - Path: /home/owncloud/apps/brute_force_protection
  - configreport:
    - Version: 0.2.1
    - Path: /home/owncloud/apps/configreport
  - dav:
    - Version: 0.7.0
    - Path: /home/owncloud/apps/dav
  - federatedfilesharing:
    - Version: 0.5.0
    - Path: /home/owncloud/apps/federatedfilesharing
  - files:
    - Version: 1.5.2
    - Path: /home/owncloud/apps/files
  - files_external:
    - Version: 0.9.0
    - Path: /home/owncloud/apps/files_external
  - files_sharing:
    - Version: 0.14.0
    - Path: /home/owncloud/apps/files_sharing
  - guests:
    - Version: 0.11.0
    - Path: /home/owncloud/apps/guests
  - market:
    - Version: 0.6.3
    - Path: /home/owncloud/apps/market
  - notifications:
    - Version: 0.5.4
    - Path: /home/owncloud/apps/notifications
  - password_policy:
    - Version: 2.1.4
    - Path: /home/owncloud/apps/password_policy
  - updatenotification:
    - Version: 0.2.1
    - Path: /home/owncloud/apps/updatenotification
Disabled:
  - admin_audit:
    - Path: /home/owncloud/apps/admin_audit
  - announcementcenter:
    - Path: /home/owncloud/apps/announcementcenter
  - comments:
    - Path: /home/owncloud/apps/comments
  - customgroups:
    - Path: /home/owncloud/apps/customgroups
  - encryption:
    - Path: /home/owncloud/apps/encryption
  - enterprise_key:
    - Path: /home/owncloud/apps/enterprise_key
  - external:
    - Path: /home/owncloud/apps/external
  - federation:
    - Path: /home/owncloud/apps/federation
  - files_antivirus:
    - Path: /home/owncloud/apps/files_antivirus
  - files_classifier:
    - Path: /home/owncloud/apps/files_classifier
  - files_external_dropbox:
    - Path: /home/owncloud/apps/files_external_dropbox
  - files_external_ftp:
    - Path: /home/owncloud/apps/files_external_ftp
  - files_ldap_home:
    - Path: /home/owncloud/apps/files_ldap_home
  - files_lifecycle:
    - Path: /home/owncloud/apps/files_lifecycle
  - files_mediaviewer:
    - Path: /home/owncloud/apps/files_mediaviewer
  - files_pdfviewer:
    - Path: /home/owncloud/apps/files_pdfviewer
  - files_texteditor:
    - Path: /home/owncloud/apps/files_texteditor
  - files_trashbin:
    - Path: /home/owncloud/apps/files_trashbin
  - files_versions:
    - Path: /home/owncloud/apps/files_versions
  - firewall:
    - Path: /home/owncloud/apps/firewall
  - firstrunwizard:
    - Path: /home/owncloud/apps/firstrunwizard
  - graphapi:
    - Path: /home/owncloud/apps/graphapi
  - metrics:
    - Path: /home/owncloud/apps/metrics
  - oauth2:
    - Path: /home/owncloud/apps/oauth2
  - openidconnect:
    - Path: /home/owncloud/apps/openidconnect
  - provisioning_api:
    - Path: /home/owncloud/apps/provisioning_api
  - ransomware_protection:
    - Path: /home/owncloud/apps/ransomware_protection
  - sharepoint:
    - Path: /home/owncloud/apps/sharepoint
  - systemtags:
    - Path: /home/owncloud/apps/systemtags
  - systemtags_management:
    - Path: /home/owncloud/apps/systemtags_management
  - templateeditor:
    - Path: /home/owncloud/apps/templateeditor
  - theme-enterprise:
    - Path: /home/owncloud/apps/theme-enterprise
  - user_external:
    - Path: /home/owncloud/apps/user_external
  - user_ldap:
    - Path: /home/owncloud/apps/user_ldap
  - user_shibboleth:
    - Path: /home/owncloud/apps/user_shibboleth
  - web:
    - Path: /home/owncloud/apps/web
  - windows_network_drive:
    - Path: /home/owncloud/apps/windows_network_drive
  - wopi:
    - Path: /home/owncloud/apps/wopi
  - workflow:
    - Path: /home/owncloud/apps/workflow
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none

### Client configuration
**Browser:** Firefox 101.0.1 (64-bit) and Chrome 102.0.5005.115 (64-bit)

**Operating system:** Windows 10, 21H2

#### Web server error log
```
No errors are logged
```

#### ownCloud log (data/owncloud.log)
```
No errors are logged
```

#### Browser log
```
No errors are logged
```
[generated_config.txt](https://github.com/owncloud/guests/files/9538321/generated_config.txt)
